// <auto-generated />
using System;
using Arya.BabyLogger.WebApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arya.BabyLogger.WebApi.Db.Migrations
{
    [DbContext(typeof(BabyLoggerDbContext))]
    [Migration("20260212112154_Set CareHolders related Table required CareHolderId to rename CareHouseHolders Table")]
    partial class SetCareHoldersrelatedTablerequiredCareHolderIdtorenameCareHouseHoldersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.BreastPumpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountML")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CareHolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CareHouseholdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PumpTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareHolderId");

                    b.HasIndex("CareHouseholdId");

                    b.HasIndex("PumpTime");

                    b.ToTable("BreastPumps");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.CareHolderEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CareHolders", (string)null);
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.CareHouseholdEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CareHouseholds", (string)null);
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.ExcretionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Consistency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcretionColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExcretionDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExcretionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Excretions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Consistency = "Watery",
                            ExcretionColor = "#FFFF00",
                            ExcretionDateTime = new DateTime(2026, 1, 12, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 1,
                            Note = "Normal"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Consistency = "Soft",
                            ExcretionColor = "#8B7355",
                            ExcretionDateTime = new DateTime(2026, 1, 11, 6, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 2,
                            Note = "Soft stool"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Consistency = "Hard",
                            ExcretionColor = "#A9A9A9",
                            ExcretionDateTime = new DateTime(2026, 1, 10, 6, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 3,
                            Note = "Slightly hard"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Consistency = "Paste",
                            ExcretionColor = "#DAA520",
                            ExcretionDateTime = new DateTime(2026, 1, 9, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 4,
                            Note = "Watery"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Consistency = "Liquid",
                            ExcretionColor = "#808080",
                            ExcretionDateTime = new DateTime(2026, 1, 8, 6, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 5,
                            Note = "Normal consistency"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Consistency = "Watery",
                            ExcretionColor = "#FFFF00",
                            ExcretionDateTime = new DateTime(2026, 1, 7, 6, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 6
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Consistency = "Soft",
                            ExcretionColor = "#8B7355",
                            ExcretionDateTime = new DateTime(2026, 1, 6, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 7
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Consistency = "Hard",
                            ExcretionColor = "#A9A9A9",
                            ExcretionDateTime = new DateTime(2026, 1, 12, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 8,
                            Note = "Changed diet"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Consistency = "Paste",
                            ExcretionColor = "#DAA520",
                            ExcretionDateTime = new DateTime(2026, 1, 11, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 9,
                            Note = "Morning"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Consistency = "Liquid",
                            ExcretionColor = "#808080",
                            ExcretionDateTime = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 10,
                            Note = "After feeding"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Consistency = "Watery",
                            ExcretionColor = "#FFFF00",
                            ExcretionDateTime = new DateTime(2026, 1, 9, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Consistency = "Soft",
                            ExcretionColor = "#8B7355",
                            ExcretionDateTime = new DateTime(2026, 1, 8, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Consistency = "Hard",
                            ExcretionColor = "#A9A9A9",
                            ExcretionDateTime = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 3,
                            Note = "Healthy"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Consistency = "Paste",
                            ExcretionColor = "#DAA520",
                            ExcretionDateTime = new DateTime(2026, 1, 6, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 4,
                            Note = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Consistency = "Liquid",
                            ExcretionColor = "#808080",
                            ExcretionDateTime = new DateTime(2026, 1, 12, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 5
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Consistency = "Watery",
                            ExcretionColor = "#FFFF00",
                            ExcretionDateTime = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 6,
                            Note = "Normal"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Consistency = "Soft",
                            ExcretionColor = "#8B7355",
                            ExcretionDateTime = new DateTime(2026, 1, 10, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 7,
                            Note = "Soft stool"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Consistency = "Hard",
                            ExcretionColor = "#A9A9A9",
                            ExcretionDateTime = new DateTime(2026, 1, 9, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 8,
                            Note = "Slightly hard"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Consistency = "Paste",
                            ExcretionColor = "#DAA520",
                            ExcretionDateTime = new DateTime(2026, 1, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 9,
                            Note = "Watery"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Consistency = "Liquid",
                            ExcretionColor = "#808080",
                            ExcretionDateTime = new DateTime(2026, 1, 7, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 10,
                            Note = "Normal consistency"
                        });
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.FeedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.SleepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SleepEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SleepStartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SleepEndTime");

                    b.HasIndex("SleepStartTime");

                    b.ToTable("Sleeps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Note = "Overnight sleep",
                            SleepEndTime = new DateTime(2026, 1, 12, 2, 0, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Note = "Night wake",
                            SleepEndTime = new DateTime(2026, 1, 12, 4, 30, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 12, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Note = "Morning nap",
                            SleepEndTime = new DateTime(2026, 1, 12, 7, 0, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 12, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            Note = "Overnight sleep",
                            SleepEndTime = new DateTime(2026, 1, 11, 2, 15, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            Note = "Early morning nap",
                            SleepEndTime = new DateTime(2026, 1, 11, 5, 0, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 11, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            Note = "Morning nap",
                            SleepEndTime = new DateTime(2026, 1, 11, 8, 20, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 11, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            Note = "Overnight sleep",
                            SleepEndTime = new DateTime(2026, 1, 10, 2, 10, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            Note = "Night wake",
                            SleepEndTime = new DateTime(2026, 1, 10, 4, 0, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 10, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222209"),
                            Note = "Morning nap",
                            SleepEndTime = new DateTime(2026, 1, 10, 7, 15, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 10, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222210"),
                            Note = "Overnight sleep",
                            SleepEndTime = new DateTime(2026, 1, 9, 1, 50, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222211"),
                            Note = "Night wake",
                            SleepEndTime = new DateTime(2026, 1, 9, 4, 10, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 9, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222212"),
                            Note = "Morning nap",
                            SleepEndTime = new DateTime(2026, 1, 9, 7, 0, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 9, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222213"),
                            Note = "Overnight sleep",
                            SleepEndTime = new DateTime(2026, 1, 8, 2, 25, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222214"),
                            Note = "Night wake",
                            SleepEndTime = new DateTime(2026, 1, 8, 4, 5, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 8, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222215"),
                            Note = "Morning nap",
                            SleepEndTime = new DateTime(2026, 1, 8, 7, 35, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 8, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222216"),
                            Note = "Overnight sleep",
                            SleepEndTime = new DateTime(2026, 1, 7, 2, 0, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222217"),
                            Note = "Night wake",
                            SleepEndTime = new DateTime(2026, 1, 7, 4, 20, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 7, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222218"),
                            Note = "Morning nap",
                            SleepEndTime = new DateTime(2026, 1, 7, 7, 10, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 7, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222219"),
                            Note = "Overnight sleep",
                            SleepEndTime = new DateTime(2026, 1, 6, 2, 30, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222220"),
                            Note = "Night wake",
                            SleepEndTime = new DateTime(2026, 1, 6, 4, 0, 0, 0, DateTimeKind.Utc),
                            SleepStartTime = new DateTime(2026, 1, 6, 3, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CareHolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CareHouseholdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareHolderId");

                    b.HasIndex("CareHouseholdId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.BreastPumpEntity", b =>
                {
                    b.HasOne("Arya.BabyLogger.WebApi.Db.CareHolderEntity", "CareHolder")
                        .WithMany()
                        .HasForeignKey("CareHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arya.BabyLogger.WebApi.Db.CareHouseholdEntity", "CareHousehold")
                        .WithMany()
                        .HasForeignKey("CareHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareHolder");

                    b.Navigation("CareHousehold");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.UserEntity", b =>
                {
                    b.HasOne("Arya.BabyLogger.WebApi.Db.CareHolderEntity", "CareHolder")
                        .WithMany()
                        .HasForeignKey("CareHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arya.BabyLogger.WebApi.Db.CareHouseholdEntity", "CareHousehold")
                        .WithMany()
                        .HasForeignKey("CareHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareHolder");

                    b.Navigation("CareHousehold");
                });
#pragma warning restore 612, 618
        }
    }
}
