// <auto-generated />
using System;
using Arya.BabyLogger.WebApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arya.BabyLogger.WebApi.Db.Migrations
{
    [DbContext(typeof(BabyLoggerDbContext))]
    [Migration("20260502000248_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.BreastPumpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountML")
                        .HasColumnType("int");

                    b.Property<Guid>("CareHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PumpTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CareHolderId");

                    b.HasIndex("PumpTime");

                    b.ToTable("BreastPumps");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.BreastPumpSettingEntity", b =>
                {
                    b.Property<Guid>("CareHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PumpIntervalHours")
                        .HasColumnType("int");

                    b.HasKey("CareHolderId");

                    b.ToTable("BreastPumpSettings", (string)null);
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.CareHolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InviteUserEmail")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CareHolders", (string)null);
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.ExcretionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consistency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcretionColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExcretionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExcretionLevel")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Excretions");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.FeedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.ResetPasswordRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ResetPasswordRequests");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.SleepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SleepEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SleepStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SleepEndTime");

                    b.HasIndex("SleepStartTime");

                    b.ToTable("Sleeps");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CareHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("CareHolderId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.BreastPumpEntity", b =>
                {
                    b.HasOne("Arya.BabyLogger.WebApi.Db.CareHolderEntity", "CareHolder")
                        .WithMany()
                        .HasForeignKey("CareHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareHolder");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.BreastPumpSettingEntity", b =>
                {
                    b.HasOne("Arya.BabyLogger.WebApi.Db.CareHolderEntity", "CareHolder")
                        .WithMany()
                        .HasForeignKey("CareHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareHolder");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.ResetPasswordRequestEntity", b =>
                {
                    b.HasOne("Arya.BabyLogger.WebApi.Db.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.UserEntity", b =>
                {
                    b.HasOne("Arya.BabyLogger.WebApi.Db.CareHolderEntity", "CareHolder")
                        .WithMany()
                        .HasForeignKey("CareHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareHolder");
                });
#pragma warning restore 612, 618
        }
    }
}
