// <auto-generated />
using System;
using Arya.BabyLogger.WebApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arya.BabyLogger.WebApi.Db.Migrations
{
    [DbContext(typeof(BabyLoggerDbContext))]
    [Migration("20260112090504_Add Column Consistency to Excretion Table")]
    partial class AddColumnConsistencytoExcretionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.ExcretionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Consistency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcretionColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExcretionDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExcretionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Excretions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Consistency = "Watery",
                            ExcretionColor = "#FFFF00",
                            ExcretionDateTime = new DateTime(2026, 1, 12, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 1,
                            Note = "Normal"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Consistency = "Soft",
                            ExcretionColor = "#8B7355",
                            ExcretionDateTime = new DateTime(2026, 1, 11, 6, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 2,
                            Note = "Soft stool"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Consistency = "Hard",
                            ExcretionColor = "#A9A9A9",
                            ExcretionDateTime = new DateTime(2026, 1, 10, 6, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 3,
                            Note = "Slightly hard"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Consistency = "Paste",
                            ExcretionColor = "#DAA520",
                            ExcretionDateTime = new DateTime(2026, 1, 9, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 4,
                            Note = "Watery"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Consistency = "Liquid",
                            ExcretionColor = "#808080",
                            ExcretionDateTime = new DateTime(2026, 1, 8, 6, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 5,
                            Note = "Normal consistency"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Consistency = "Watery",
                            ExcretionColor = "#FFFF00",
                            ExcretionDateTime = new DateTime(2026, 1, 7, 6, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 6
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Consistency = "Soft",
                            ExcretionColor = "#8B7355",
                            ExcretionDateTime = new DateTime(2026, 1, 6, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 7
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Consistency = "Hard",
                            ExcretionColor = "#A9A9A9",
                            ExcretionDateTime = new DateTime(2026, 1, 12, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 8,
                            Note = "Changed diet"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Consistency = "Paste",
                            ExcretionColor = "#DAA520",
                            ExcretionDateTime = new DateTime(2026, 1, 11, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 9,
                            Note = "Morning"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Consistency = "Liquid",
                            ExcretionColor = "#808080",
                            ExcretionDateTime = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 10,
                            Note = "After feeding"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Consistency = "Watery",
                            ExcretionColor = "#FFFF00",
                            ExcretionDateTime = new DateTime(2026, 1, 9, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Consistency = "Soft",
                            ExcretionColor = "#8B7355",
                            ExcretionDateTime = new DateTime(2026, 1, 8, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Consistency = "Hard",
                            ExcretionColor = "#A9A9A9",
                            ExcretionDateTime = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 3,
                            Note = "Healthy"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Consistency = "Paste",
                            ExcretionColor = "#DAA520",
                            ExcretionDateTime = new DateTime(2026, 1, 6, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 4,
                            Note = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Consistency = "Liquid",
                            ExcretionColor = "#808080",
                            ExcretionDateTime = new DateTime(2026, 1, 12, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 5
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Consistency = "Watery",
                            ExcretionColor = "#FFFF00",
                            ExcretionDateTime = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 6,
                            Note = "Normal"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Consistency = "Soft",
                            ExcretionColor = "#8B7355",
                            ExcretionDateTime = new DateTime(2026, 1, 10, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 7,
                            Note = "Soft stool"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Consistency = "Hard",
                            ExcretionColor = "#A9A9A9",
                            ExcretionDateTime = new DateTime(2026, 1, 9, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 8,
                            Note = "Slightly hard"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Consistency = "Paste",
                            ExcretionColor = "#DAA520",
                            ExcretionDateTime = new DateTime(2026, 1, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 9,
                            Note = "Watery"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Consistency = "Liquid",
                            ExcretionColor = "#808080",
                            ExcretionDateTime = new DateTime(2026, 1, 7, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            ExcretionLevel = 10,
                            Note = "Normal consistency"
                        });
                });

            modelBuilder.Entity("Arya.BabyLogger.WebApi.Db.FeedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });
#pragma warning restore 612, 618
        }
    }
}
